# name: Correção

# on:
#   pull_request:
#     types: [ synchronize, opened, reopened ]
#     branches: [ "gh-pages" ]

# env:
#   JEKYLL_PATH: "${{ github.workspace }}/_site"

# jobs:
#   setup:
#     name: Setup do projeto
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout do repositório
#         uses: actions/checkout@v2
  
#       - name: Build Jekyll
#         run: |
#           docker run \
#           -v ${{ github.workspace }}:/srv/jekyll -v ${{ env.JEKYLL_PATH }}/:/srv/jekyll/_site \
#           jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

#       - name: Ajustes de permissão
#         run: sudo chown -R $(whoami):$(id -ng) ${{ env.JEKYLL_PATH }}

#       - name: Preparação dos testes
#         uses: actions/setup-node@v2
#         with: 
#           node-version: 16.x
#           cache: 'npm'

#       - name: Configuração das dependências
#         run: npm install

#       - name: Caching do projeto
#         uses: actions/cache@v2
#         with:
#           path: |
#             ${{ env.JEKYLL_PATH }}/
#             ${{ github.workspace }}/tests/
#             ${{ github.workspace }}/node_modules/
#             ${{ github.workspace }}/package-lock.json
#             ${{ github.workspace }}/package.json
#           key: ${{ runner.os }}-${{ github.run_id }}

#   grading-json-file:
#     name: "Exercício: Mural dos Estudantes"
#     needs: setup
#     runs-on: ubuntu-latest
#     strategy:
#       matrix: 
#         test: [ "T1", "T2", "T3" ]

#     steps:
#       - name: Carregando cache do projeto
#         uses: actions/cache@v2
#         with:
#           path: |
#             ${{ env.JEKYLL_PATH }}/
#             ${{ github.workspace }}/tests/
#             ${{ github.workspace }}/node_modules/
#             ${{ github.workspace }}/package-lock.json
#             ${{ github.workspace }}/package.json
#           key: ${{ runner.os }}-${{ github.run_id }}

#       - name: "${{ matrix.test }}"
#         if: ${{ always() }}
#         run: npm test -- -t "${{ matrix.test }}"