name: Correção

on:
  push: 
    branches: [ "gh-pages" ]

env:
  JEKYLL_PATH: "${{ github.workspace }}/_site"

jobs:
  setup:
    name: Setup do projeto
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v2
  
      - name: Build Jekyll
        run: |
          docker run \
          -v ${{ github.workspace }}:/srv/jekyll -v ${{ env.JEKYLL_PATH }}/:/srv/jekyll/_site \
          jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

      - name: Preparação dos testes
        uses: actions/setup-node@v2
        with: 
          node-version: 16.x
          cache: 'npm'

      - name: Configuração das dependências
        run: npm install

      - name: Caching do projeto
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.JEKYLL_PATH }}/
            ${{ github.workspace }}/tests/
            ${{ github.workspace }}/package-lock.json
            ${{ github.workspace }}/package.json
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

  grading:
    name: Correção
    needs: setup
    runs-on: ubuntu-latest

    steps:
      - name: Carregando cache do projeto
        uses: actions/cache@v2
        with:
          path: |
            ${{ env.JEKYLL_PATH }}/
            ${{ github.workspace }}/tests/
            ${{ github.workspace }}/package-lock.json
            ${{ github.workspace }}/package.json
          key: ${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Arquivo adicionado
        run: npm test -- -t "1."
      - name: Descrição adicionada
        run: npm test -- -t "2."
      - name: Emoji adicionado
        run: npm test -- -t "3."